version: "3.7"

services:
  api:
    container_name: "mapnotes-api"
    image: launchcodedevops/mapnotes-api-node
    ports:
      - "8008:8008"
  client:
    container_name: "mapnotes-client"
    image: python
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/dist:/client:ro"
    command: "python -m http.server -d /client 3000"
